CONFIG:
  PATH_CONFIG: config.yaml

  DIR_TEMPLATE: templates
  DIR_TEMPLATE_DEFAULT: templates
  TEMPLATE_FILE_DEFAULT: template.html

  PATH_DIR: directory
  PATH_DIR_DEFAULT: contents

  PATH_STATIC: static
  PATH_STATIC_DEFAULT: static

  PATH_SCSS: scss
  PATH_CSS: css

  DB: db
  DB_URL: url
  DB_URL_DEFAULT: 'sqlite:///test.db'

  CATEGORY: category
  SECURITY_HEADERS: security_headers
  FONTS: fonts

  SITE_NAME: site_name
  SITE_NAME_DEFAULT: site name
  BASE_URL: base_url
  BASE_URL_DEFAULT: '/'

  DIR_INDEX: dir_index
  DIR_INDEX_DEFAULT: index

OGP:
  OGP_DIC: ogp
  IMAGE: image
  DESCRIPTION: description
  DESCRIPTION_ERROR: desc_error
  DESCRIPTION_ERROR_DEFAULT: error


jinja2:
  DIR_TEMPLATES: templates
  EXT: j2